# Generated by Django 4.0.5 on 2022-08-23 12:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the characters first name', max_length=100, validators=[django.core.validators.MaxLengthValidator])),
                ('last_name', models.CharField(help_text='Enter the characters last name', max_length=100, validators=[django.core.validators.MaxLengthValidator])),
                ('summary', models.TextField(blank=True, help_text="Enter character's biography", max_length=1000, null=True, validators=[django.core.validators.MaxLengthValidator])),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter date of birth.', null=True)),
                ('date_of_death', models.DateField(help_text='Enter date of death.', null=True, verbose_name='Died')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the group.', max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('characters', models.ManyToManyField(blank=True, help_text='Use command + click to select multiple characters.', null=True, to='reddead.character')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddead.question')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='related_gang',
            field=models.ForeignKey(help_text='Enter group information.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reddead.group'),
        ),
    ]
